name: svg_path_transform
description: Pure dart library for parsing and manipulating SVG paths, such as rotating, translating, etc.
version: 1.2.0
repository: https://github.com/bramp/svg_path_transform

funding:
  - https://www.buymeacoffee.com/bramp

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  meta: ^1.18.2
  path_parsing: ^1.1.0

dev_dependencies:
  test: ^1.31.0
  very_good_analysis: ^10.2.0
